name: TodoMVC Cucumber Tests
on:
  push:
    branches: [main, tests]
jobs:
  e2e-tests:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Set up Playwright
        uses: microsoft/playwright-github-action@v1

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Create env file
        run: |
          touch .env
          echo URL=${{ secrets.URL }} >> .env
          cat .env

      - name: Create Qase Run
        run: npm run qase-run

      - name: Complete Run
        run: |
          gh run cancel ${{ github.run_id }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
