name: TodoMVC Cucumber Tests

on: workflow_dispatch

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Set up Playwright
        uses: microsoft/playwright-github-action@v1

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Create env file
        run: |
          touch .env
          echo URL=${{ secrets.URL }} >> .env
          echo QASE_TESTOPS_API_TOKEN=${{ secrets.QASE_TOKEN }} >> .env
          cat .env

      - name: Configure Qase
        uses: cschleiden/replace-tokens@v1
        with:
          files: "qase.config.json"
        env:
          QASE_TOKEN: ${{ secrets.QASE_TOKEN }}

      - name: Run Cucumber Tests
        run: npm run qase-run

      - name: Upload Report
        uses: actions/upload-artifact@v4.3.3
        if: always()
        with:
          name: cucumber-report.html
          path: ./report/**
          retention-days: 5

      - name: Upload screenshots
        uses: actions/upload-artifact@v4.3.3
        if: always()
        with:
          name: screenshots
          path: ./screenshots
          retention-days: 5

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
