name: TodoMVC Cucumber Tests
on:
  push:
    branches: [main, tests]
jobs:
  e2e-tests:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Set up Playwright
        uses: microsoft/playwright-github-action@v1

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Create env file
        run: |
          touch .env
          echo URL=${{ secrets.URL }} >> .env
          cat .env

      - name: Create Qase Run
        id: run_tests
        run: |
          (
            sleep 60
            echo "Cucumber tests timed out after 1 minute."
            kill $$
          ) & 
          npm run qase-run
          TEST_EXIT_CODE=$?
          if [ $TEST_EXIT_CODE -eq 124 ]; then
            echo "Cucumber tests timed out after 10 minutes."
            exit 1
          elif [ $TEST_EXIT_CODE -ne 0 ]; then
            echo "Cucumber tests failed."
            exit $TEST_EXIT_CODE
          fi

      - name: Notify on failure
        if: failure()
        run: echo "Cucumber test failed."

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
