name: TodoMVC Cucumber Tests
on: push
jobs:
  e2e-tests:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Set up Playwright
        uses: microsoft/playwright-github-action@v1

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Show env var
        run: |
          echo $URL

      - name: Run tests
        run: npm run test
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ env.URL }}
