name: TodoMVC Cucumber Tests
on:
  push:
    branches: [main, tests]
jobs:
  e2e-tests:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Set up Playwright
        uses: microsoft/playwright-github-action@v1

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Install gtimeout
        run: brew install coreutils

      - name: Create env file
        run: |
          touch .env
          echo URL=${{ secrets.URL }} >> .env
          cat .env

      - name: Run Cucumber tests with timeout
        id: run_tests
        run: |
          gtimeout 1m npm run qase-run || {
            TEST_EXIT_CODE=$?
            if [ $TEST_EXIT_CODE -eq 124 ]; then
              echo "Cucumber tests timed out after 1 minute."
            else
              echo "Cucumber tests failed with exit code $TEST_EXIT_CODE."
            fi
            exit $TEST_EXIT_CODE
          }

      - name: Notify on failure
        if: failure()
        run: echo "Cucumber test failed."

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
