name: TodoMVC Cucumber Tests
on:
  schedule:
    - cron: "30 20 * * 1"

  push:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Set up Playwright
        uses: microsoft/playwright-github-action@v1

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Create env file
        run: |
          touch .env
          echo URL=${{ secrets.URL }} >> .env
          echo QASE_TESTOPS_API_TOKEN=${{ secrets.QASE_TOKEN }} >> .env
          cat .env

      - name: Configure Qase
        uses: cschleiden/replace-tokens@v1
        with:
          files: "qase.config.json"
        env:
          QASE_TOKEN: ${{ secrets.QASE_TOKEN }}

      - name: Run Cucumber tests
        run: npm run qase-run

      - name: Create report
        uses: mt185252/cucumber-html-report-generator@v1
        with:
          report-theme: "bootstrap"
          json-file-path: ".report/report.json"

      - name: Upload HTML report
        id: artifact_upload
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: ".report/report.html"
          if-no-files-found: error
          retention-days: 7

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
